spring:
  application:
    name: movie
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      profile: dev

  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect